theme: jekyll-theme-tactile
title: Welcome to drfennell's homepage
description: I'm teaching myself coding so you probably shouldn't expect any really exciting projects right off the bat. It'll start off mainly as the normal newbie type stuff. 
